## task2-SqlDataExtraction

## SQL Fundamentals

In [1]:
#Installing  Required Libraries
!pip install pandas sqlalchemy

Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in .\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: numpy>=2.3.3 in .\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in .\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#Import Libraries
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

In [7]:
df = pd.read_csv("SampleSuperStoreCleaned.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
df.shape

(9994, 21)

In [10]:
#Check Column Names
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

## Creating SQLite Database

In [11]:
conn = sqlite3.connect("superstore.db")

In [13]:
# Import CSV Data Into SQLite
df.to_sql( "sales", conn, if_exists="replace", index=False)

9994

In [17]:
# Testing  First SQL Query
query = """
SELECT *
FROM sales
LIMIT 5;
"""
result = pd.read_sql(query, conn)
result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# Basic SQL Queries

In [21]:
# Select:
query = """
SELECT "Order ID", "Product Name", Sales, Profit
FROM sales
LIMIT 10;
"""

pd.read_sql(query, conn)

,Order ID,Product Name,Sales,Profit
0,CA-2016-152156,Bush Somerset Collection Bookcase,261.9600,41.9136
1,CA-2016-152156,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,219.5820
2,CA-2016-138688,Self-Adhesive Address Labels for Typewriters b...,14.6200,6.8714
3,US-2015-108966,Bretford CR4500 Series Slim Rectangular Table,957.5775,-383.0310
4,US-2015-108966,Eldon Fold 'N Roll Cart System,22.3680,2.5164
5,CA-2014-115812,Eldon Expressions Wood and Plastic Desk Access...,48.8600,14.1694
6,CA-2014-115812,Newell 322,7.2800,1.9656
7,CA-2014-115812,Mitel 5320 IP Phone VoIP phone,907.1520,90.7152
8,CA-2014-115812,DXL Angle-View Binders with Locking Rings by S...,18.5040,5.7825
9,CA-2014-115812,Belkin F5C206VTEL 6 Outlet Surge,114.9000,34.4700

In [22]:
# WHERE
query = """
SELECT *
FROM sales
WHERE Sales > 500;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
1,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
2,8,CA-2014-115812,2014-06-09,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
3,11,CA-2014-115812,2014-06-09,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
4,12,CA-2014-115812,2014-06-09,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,9932,CA-2015-104948,2015-11-13,11/17/2015,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,92404,West,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960
1158,9943,CA-2014-143371,2014-12-28,01-03-2015,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,92804,West,OFF-ST-10001128,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",998.8200,9,0.00,29.9646
1159,9948,CA-2017-121559,2017-06-01,06-03-2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.8800,6,0.00,539.2464
1160,9949,CA-2017-121559,2017-06-01,06-03-2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.2000,8,0.00,793.7160
1161,9969,CA-2017-153871,2017-12-11,12/17/2017,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,...,7060,East,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.9800,2,0.00,331.1910

In [23]:
#ORDER BY
query = """
SELECT *
FROM sales
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2698,CA-2014-145317,2014-03-18,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
1,6827,CA-2016-118689,2016-10-02,10-09-2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2,8154,CA-2017-140151,2017-03-23,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
3,2624,CA-2017-127180,2017-10-22,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4,4191,CA-2017-166709,2017-11-17,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
5,9040,CA-2016-117121,2016-12-17,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
6,4099,CA-2014-116904,2014-09-23,9/28/2014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
7,4278,US-2016-107440,2016-04-16,4/20/2016,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,...,8701,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,0.0,2365.9818
8,8489,CA-2016-158841,2016-02-02,02-04-2016,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840
9,6426,CA-2016-143714,2016-05-23,5/27/2016,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,...,19120,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,4,0.4,1119.9968

In [24]:
# LIMIT
query = """
SELECT *
FROM sales
LIMIT 5;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [25]:
#GROUP BY
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [26]:
# HAVING
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
HAVING SUM(Sales) > 100000;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [30]:
# JOIN
customers = df[
    ["Customer ID", "Customer Name", "Segment"]
].drop_duplicates()

In [31]:
customers.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

793

In [32]:
query = """
SELECT
    s."Order ID",
    s."Customer ID",
    c."Customer Name",
    c."Segment",
    s.Sales
FROM sales s
JOIN customers c
ON s."Customer ID" = c."Customer ID"
LIMIT 10;
"""

pd.read_sql(query, conn)

         Order ID Customer ID    Customer Name    Segment     Sales
0  CA-2016-152156    CG-12520      Claire Gute   Consumer  261.9600
1  CA-2016-152156    CG-12520      Claire Gute   Consumer  731.9400
2  CA-2016-138688    DV-13045  Darrin Van Huff  Corporate   14.6200
3  US-2015-108966    SO-20335   Sean O'Donnell   Consumer  957.5775
4  US-2015-108966    SO-20335   Sean O'Donnell   Consumer   22.3680
5  CA-2014-115812    BH-11710  Brosina Hoffman   Consumer   48.8600
6  CA-2014-115812    BH-11710  Brosina Hoffman   Consumer    7.2800
7  CA-2014-115812    BH-11710  Brosina Hoffman   Consumer  907.1520
8  CA-2014-115812    BH-11710  Brosina Hoffman   Consumer   18.5040
9  CA-2014-115812    BH-11710  Brosina Hoffman   Consumer  114.9000

## Advanced SQL

In [33]:
# 1. Subquery
query = """
SELECT
    "Product Name",
    Sales
FROM sales
WHERE Sales > (
    SELECT AVG(Sales)
    FROM sales
)
ORDER BY Sales DESC;
"""

pd.read_sql(query, conn)

                                           Product Name      Sales
0     Cisco TelePresence System EX90 Videoconferenci...  22638.480
1                 Canon imageCLASS 2200 Advanced Copier  17499.950
2                 Canon imageCLASS 2200 Advanced Copier  13999.960
3                 Canon imageCLASS 2200 Advanced Copier  11199.968
4                 Canon imageCLASS 2200 Advanced Copier  10499.970
...                                                 ...        ...
2355                         Bevis Steel Folding Chairs    230.280
2356                         Bevis Steel Folding Chairs    230.280
2357                         Bevis Steel Folding Chairs    230.280
2358                         Bevis Steel Folding Chairs    230.280
2359      Space Solutions HD Industrial Steel Shelving.    229.940

[2360 rows x 2 columns]

In [34]:
# CTE=Common Table Expression:
query = """
WITH category_sales AS (
    SELECT
        Category,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Category
)
SELECT *
FROM category_sales
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [35]:
# Window Function
query = """
SELECT
    "Product Name",
    Sales,
    RANK() OVER (
        ORDER BY Sales DESC
    ) AS Sales_Rank
FROM sales
LIMIT 20;
"""

pd.read_sql(query, conn)

                                         Product Name      Sales  Sales_Rank
0   Cisco TelePresence System EX90 Videoconferenci...  22638.480           1
1               Canon imageCLASS 2200 Advanced Copier  17499.950           2
2               Canon imageCLASS 2200 Advanced Copier  13999.960           3
3               Canon imageCLASS 2200 Advanced Copier  11199.968           4
4               Canon imageCLASS 2200 Advanced Copier  10499.970           5
5    GBC Ibimaster 500 Manual ProClick Binding System   9892.740           6
6                Ibico EPK-21 Electric Binding System   9449.950           7
7    3D Systems Cube Printer, 2nd Generation, Magenta   9099.930           8
8   HP Designjet T520 Inkjet Large Format Printer ...   8749.950           9
9               Canon imageCLASS 2200 Advanced Copier   8399.976          10
10        High Speed Automatic Electric Letter Opener   8187.650          11
11          Lexmark MX611dhe Monochrome Laser Printer   8159.952          12
12          Cubify CubeX 3D Printer Triple Head Print   7999.980          13
13  HP Designjet T520 Inkjet Large Format Printer ...   6999.960          14
14  Fellowes PB500 Electric Punch Plastic Comb Bin...   6354.950          15
15          GBC DocuBind P400 Electric Binding System   5443.960          16
16               Hewlett Packard LaserJet 3310 Copier   5399.910          17
17   3D Systems Cube Printer, 2nd Generation, Magenta   5199.960          18
18  Fellowes PB500 Electric Punch Plastic Comb Bin...   5083.960          19
19        High Speed Automatic Electric Letter Opener   4912.590          20

In [36]:
# LAG
query = """
SELECT
    "Order Date",
    Sales,
    LAG(Sales) OVER (
        ORDER BY "Order Date"
    ) AS Previous_Sales
FROM sales
LIMIT 20;
"""

pd.read_sql(query, conn)

    Order Date     Sales  Previous_Sales
0   2014-01-03    16.448             NaN
1   2014-01-04    11.784          16.448
2   2014-01-04   272.736          11.784
3   2014-01-04     3.540         272.736
4   2014-01-05    19.536           3.540
5   2014-01-06    19.440          19.536
6   2014-01-06    12.780          19.440
7   2014-01-06  2573.820          12.780
8   2014-01-06   609.980        2573.820
9   2014-01-06     5.480         609.980
10  2014-01-06   391.980           5.480
11  2014-01-06   755.960         391.980
12  2014-01-06    31.120         755.960
13  2014-01-06     6.540          31.120
14  2014-01-07    76.728           6.540
15  2014-01-07    10.430          76.728
16  2014-01-09     9.344          10.430
17  2014-01-09    31.200           9.344
18  2014-01-10     2.890          31.200
19  2014-01-10    51.940           2.890

In [37]:
# Create a SQL View
query = """
CREATE VIEW IF NOT EXISTS category_sales AS
SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category;
"""

conn.execute(query)
conn.commit()

In [38]:
query = """
SELECT *
FROM category_sales
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales  Total_Profit
0       Technology  836154.0330   145454.9481
1        Furniture  741999.7953    18451.2728
2  Office Supplies  719047.0320   122490.8008

## 10 Business Questions

In [42]:
# Building  10 business questions and answering  them by using SQL

## Question 1 — What are the top 5 products by sales?

In [43]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

## Question 2 — What is the monthly sales trend?

In [44]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)

      Month  Total_Sales
0   2014-01   14236.8950
1   2014-02    4519.8920
2   2014-03   55691.0090
3   2014-04   28295.3450
4   2014-05   23648.2870
5   2014-06   34595.1276
6   2014-07   33946.3930
7   2014-08   27909.4685
8   2014-09   81777.3508
9   2014-10   31453.3930
10  2014-11   78628.7167
11  2014-12   69545.6205
12  2015-01   18174.0756
13  2015-02   11951.4110
14  2015-03   38726.2520
15  2015-04   34195.2085
16  2015-05   30131.6865
17  2015-06   24797.2920
18  2015-07   28765.3250
19  2015-08   36898.3322
20  2015-09   64595.9180
21  2015-10   31404.9235
22  2015-11   75972.5635
23  2015-12   74919.5212
24  2016-01   18542.4910
25  2016-02   22978.8150
26  2016-03   51715.8750
27  2016-04   38750.0390
28  2016-05   56987.7280
29  2016-06   40344.5340
30  2016-07   39261.9630
31  2016-08   31115.3743
32  2016-09   73410.0249
33  2016-10   59687.7450
34  2016-11   79411.9658
35  2016-12   96999.0430
36  2017-01   43971.3740
37  2017-02   20301.1334
38  2017-03   58872.3528
39  2017-04   36521.5361
40  2017-05   44261.1102
41  2017-06   52981.7257
42  2017-07   45264.4160
43  2017-08   63120.8880
44  2017-09   87866.6520
45  2017-10   77776.9232
46  2017-11  118447.8250
47  2017-12   83829.3188

## Question 3 — Which customer segment has the highest sales?

In [45]:
query = """
SELECT
    Segment,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Segment
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

       Segment   Total_Sales
0     Consumer  1.161401e+06
1    Corporate  7.061464e+05
2  Home Office  4.296531e+05

## Question 4 — Which category generates the highest profit?

In [46]:
query = """
SELECT
    Category,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Profit DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

     Category  Total_Profit
0  Technology   145454.9481

## Question 5 — Which region has the highest sales?

In [47]:
query = """
SELECT
    Region,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

## Question 6 — What are the top 10 customers by sales?

In [48]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

## Question 7 — Which sub-category has the highest profit?

In [49]:
query = """
SELECT
    "Sub-Category",
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY "Sub-Category"
ORDER BY Total_Profit DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

  Sub-Category  Total_Profit
0      Copiers    55617.8249

## Question 8 — Which products are loss-making?

In [50]:
query = """
SELECT
    "Product Name",
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY "Product Name"
HAVING SUM(Profit) < 0
ORDER BY Total_Profit;
"""

pd.read_sql(query, conn)

                                          Product Name  Total_Profit
0            Cubify CubeX 3D Printer Double Head Print -8.879970e+03
1            Lexmark MX611dhe Monochrome Laser Printer -4.589973e+03
2            Cubify CubeX 3D Printer Triple Head Print -3.839990e+03
3    Chromcraft Bull-Nose Wood Oval Conference Tabl... -2.876116e+03
4    Bush Advantage Collection Racetrack Conference... -1.934398e+03
..                                                 ...           ...
297                                   Rubber Band Ball -2.992000e-01
298  Acco PRESSTEX Data Binder with Storage Hooks, ... -1.614000e-01
299                           Global Super Steno Chair -4.440892e-15
300        Avery Trapezoid Extra Heavy Duty 4" Binders -3.552714e-15
301                     Premier Electric Letter Opener -3.552714e-15

[302 rows x 2 columns]

## Question 9 — What is the total sales and profit?

In [51]:
query = """
SELECT
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales;
"""

pd.read_sql(query, conn)

    Total_Sales  Total_Profit
0  2.297201e+06   286397.0217

## Question 10 — Which state has the highest sales?

In [52]:
query = """
SELECT
    State,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

          State  Total_Sales
0    California  457687.6315
1      New York  310876.2710
2         Texas  170188.0458
3    Washington  138641.2700
4  Pennsylvania  116511.9140
5       Florida   89473.7080
6      Illinois   80166.1010
7          Ohio   78258.1360
8      Michigan   76269.6140
9      Virginia   70636.7200

## Python + SQLAlchemy Integration

In [53]:
engine = create_engine("sqlite:///superstore.db")

In [54]:
query = """
SELECT Category, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)

result

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

## Creating a Reusable Database Utility

In [55]:
# Creating a reusable database utility script
import sqlite3
import pandas as pd

def create_connection(database):
    return sqlite3.connect(database)

def load_csv_to_database(csv_file, database, table_name):
    conn = sqlite3.connect(database)

    df = pd.read_csv(csv_file)

    df.to_sql(
        table_name,
        conn,
        if_exists="replace",
        index=False
    )

    conn.close()

def run_query(database, query):
    conn = sqlite3.connect(database)

    result = pd.read_sql(query, conn)

    conn.close()

    return result

## Creating SQL File

In [62]:
# -- Top 5 Products by Sales
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, conn)
result

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [63]:
# -- Sales by Category
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [64]:
# Sales by Region
query = """
SELECT
    Region,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

## Subquery

In [65]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
HAVING SUM(Sales) >
(
    SELECT AVG(Product_Sales)
    FROM
    (
        SELECT
            "Product Name",
            SUM(Sales) AS Product_Sales
        FROM sales
        GROUP BY "Product Name"
    )
)
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

                                          Product Name  Total_Sales
0                Canon imageCLASS 2200 Advanced Copier    61599.824
1    Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2    Cisco TelePresence System EX90 Videoconferenci...    22638.480
3         HON 5400 Series Task Chairs for Big and Tall    21870.576
4           GBC DocuBind TL300 Electric Binding System    19823.479
..                                                 ...          ...
445                  Bush Somerset Collection Bookcase     1263.957
446                 Panasonic KX T7736-B Digital phone     1259.580
447  Logitech G430 Surround Sound Gaming Headset wi...     1247.844
448  Tripp Lite Isotel 6 Outlet Surge Protector wit...     1243.788
449                         Hon Valutask Swivel Chairs     1242.054

[450 rows x 2 columns]

In [66]:
# CTE=Common Table Expression:
query = """
WITH product_sales AS
(
    SELECT
        "Product Name",
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY "Product Name"
)

SELECT *
FROM product_sales
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

In [67]:
# ROW_NUMBER()
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales,
    ROW_NUMBER() OVER (
        ORDER BY SUM(Sales) DESC
    ) AS Product_Number
FROM sales
GROUP BY "Product Name";
"""

pd.read_sql_query(query, conn)

,Product Name,Total_Sales,Product_Number
0,Canon imageCLASS 2200 Advanced Copier,61599.824,1
1,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384,2
2,Cisco TelePresence System EX90 Videoconferenci...,22638.480,3
3,HON 5400 Series Task Chairs for Big and Tall,21870.576,4
4,GBC DocuBind TL300 Electric Binding System,19823.479,5
...,...,...,...
1845,Avery Hi-Liter Pen Style Six-Color Fluorescent...,7.700,1846
1846,Grip Seal Envelopes,7.072,1847
1847,Xerox 20,6.480,1848
1848,Avery 5,5.760,1849
1849,Eureka Disposable Bags for Sanitaire Vibra Gro...,1.624,1850

In [68]:
# RANK()
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    RANK() OVER (
        ORDER BY SUM(Sales) DESC
    ) AS Sales_Rank
FROM sales
GROUP BY Category;
"""

pd.read_sql_query(query, conn)

          Category  Total_Sales  Sales_Rank
0       Technology  836154.0330           1
1        Furniture  741999.7953           2
2  Office Supplies  719047.0320           3

In [71]:
# LAG()query = """
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY strftime('%Y-%m', "Order Date")
)

SELECT
    Month,
    Total_Sales,
    LAG(Total_Sales) OVER (
        ORDER BY Month
    ) AS Previous_Month_Sales
FROM monthly_sales
ORDER BY Month;
"""

pd.read_sql_query(query, conn)

      Month  Total_Sales  Previous_Month_Sales
0   2014-01   14236.8950                   NaN
1   2014-02    4519.8920            14236.8950
2   2014-03   55691.0090             4519.8920
3   2014-04   28295.3450            55691.0090
4   2014-05   23648.2870            28295.3450
5   2014-06   34595.1276            23648.2870
6   2014-07   33946.3930            34595.1276
7   2014-08   27909.4685            33946.3930
8   2014-09   81777.3508            27909.4685
9   2014-10   31453.3930            81777.3508
10  2014-11   78628.7167            31453.3930
11  2014-12   69545.6205            78628.7167
12  2015-01   18174.0756            69545.6205
13  2015-02   11951.4110            18174.0756
14  2015-03   38726.2520            11951.4110
15  2015-04   34195.2085            38726.2520
16  2015-05   30131.6865            34195.2085
17  2015-06   24797.2920            30131.6865
18  2015-07   28765.3250            24797.2920
19  2015-08   36898.3322            28765.3250
20  2015-09   64595.9180            36898.3322
21  2015-10   31404.9235            64595.9180
22  2015-11   75972.5635            31404.9235
23  2015-12   74919.5212            75972.5635
24  2016-01   18542.4910            74919.5212
25  2016-02   22978.8150            18542.4910
26  2016-03   51715.8750            22978.8150
27  2016-04   38750.0390            51715.8750
28  2016-05   56987.7280            38750.0390
29  2016-06   40344.5340            56987.7280
30  2016-07   39261.9630            40344.5340
31  2016-08   31115.3743            39261.9630
32  2016-09   73410.0249            31115.3743
33  2016-10   59687.7450            73410.0249
34  2016-11   79411.9658            59687.7450
35  2016-12   96999.0430            79411.9658
36  2017-01   43971.3740            96999.0430
37  2017-02   20301.1334            43971.3740
38  2017-03   58872.3528            20301.1334
39  2017-04   36521.5361            58872.3528
40  2017-05   44261.1102            36521.5361
41  2017-06   52981.7257            44261.1102
42  2017-07   45264.4160            52981.7257
43  2017-08   63120.8880            45264.4160
44  2017-09   87866.6520            63120.8880
45  2017-10   77776.9232            87866.6520
46  2017-11  118447.8250            77776.9232
47  2017-12   83829.3188           118447.8250

In [72]:
# LEAD()
query = """
WITH monthly_sales AS
(
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY strftime('%Y-%m', "Order Date")
)

SELECT
    Month,
    Total_Sales,
    LEAD(Total_Sales) OVER (
        ORDER BY Month
    ) AS Next_Month_Sales
FROM monthly_sales
ORDER BY Month;
"""

pd.read_sql_query(query, conn)

      Month  Total_Sales  Next_Month_Sales
0   2014-01   14236.8950         4519.8920
1   2014-02    4519.8920        55691.0090
2   2014-03   55691.0090        28295.3450
3   2014-04   28295.3450        23648.2870
4   2014-05   23648.2870        34595.1276
5   2014-06   34595.1276        33946.3930
6   2014-07   33946.3930        27909.4685
7   2014-08   27909.4685        81777.3508
8   2014-09   81777.3508        31453.3930
9   2014-10   31453.3930        78628.7167
10  2014-11   78628.7167        69545.6205
11  2014-12   69545.6205        18174.0756
12  2015-01   18174.0756        11951.4110
13  2015-02   11951.4110        38726.2520
14  2015-03   38726.2520        34195.2085
15  2015-04   34195.2085        30131.6865
16  2015-05   30131.6865        24797.2920
17  2015-06   24797.2920        28765.3250
18  2015-07   28765.3250        36898.3322
19  2015-08   36898.3322        64595.9180
20  2015-09   64595.9180        31404.9235
21  2015-10   31404.9235        75972.5635
22  2015-11   75972.5635        74919.5212
23  2015-12   74919.5212        18542.4910
24  2016-01   18542.4910        22978.8150
25  2016-02   22978.8150        51715.8750
26  2016-03   51715.8750        38750.0390
27  2016-04   38750.0390        56987.7280
28  2016-05   56987.7280        40344.5340
29  2016-06   40344.5340        39261.9630
30  2016-07   39261.9630        31115.3743
31  2016-08   31115.3743        73410.0249
32  2016-09   73410.0249        59687.7450
33  2016-10   59687.7450        79411.9658
34  2016-11   79411.9658        96999.0430
35  2016-12   96999.0430        43971.3740
36  2017-01   43971.3740        20301.1334
37  2017-02   20301.1334        58872.3528
38  2017-03   58872.3528        36521.5361
39  2017-04   36521.5361        44261.1102
40  2017-05   44261.1102        52981.7257
41  2017-06   52981.7257        45264.4160
42  2017-07   45264.4160        63120.8880
43  2017-08   63120.8880        87866.6520
44  2017-09   87866.6520        77776.9232
45  2017-10   77776.9232       118447.8250
46  2017-11  118447.8250        83829.3188
47  2017-12   83829.3188               NaN

## Create a View

In [73]:
query = """
CREATE VIEW IF NOT EXISTS category_sales AS
SELECT
    Category,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category;
"""

conn.execute(query)
conn.commit()

In [74]:
query = """
SELECT *
FROM category_sales
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

          Category  Total_Sales  Total_Profit
0       Technology  836154.0330   145454.9481
1        Furniture  741999.7953    18451.2728
2  Office Supplies  719047.0320   122490.8008